name: sapatekno_mvvm
description: Flutter MVVM architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0
  easy_localization: ^3.0.0
  flutter_flavor: ^3.0.3
  flutter_screenutil: ^5.3.1
  pmvvm: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/