name: sapatekno_mvvm
description: Flutter MVVM architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0
  dio: ^4.0.4
  dio_log: ^2.0.2
  easy_localization: ^3.0.0
  flutter_flavor: ^3.0.3
  flutter_screenutil: ^5.3.1
  flutter_svg_provider: ^1.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  pmvvm: ^3.0.0
  pull_to_refresh: ^2.0.0
  shimmer_animation: ^2.1.0+1
  talker: ^0.8.0
  talker_flutter: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.5
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/